name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ 安装 Flutter（你也可以指定特定版本）
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"
          cache: true

      # ✅ 获取依赖
      - name: Install dependencies
        run: flutter pub get
      - name: Install In18
        run: flutter gen-l10n
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Create version tag
        run: |
          git tag 'v1.0.1'  # 使用时间戳创建标签
          git push origin --tags  # 推送标签到 GitHub
        
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
